import { AlertCircle, ArrowDown, ArrowUp, Check, Download, FolderPlus, Import, Library, LoaderCircle, Pencil, Play, Plus, RefreshCw, Save, Search, Trash2, X } from 'lucide-react';
import { useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api, jsonBody } from '../api';
import { useAppState } from '../state/AppState';
import type { Course, Lesson } from '../types';

type ContentDraft = { mode: 'create' | 'edit'; lessonId?: string; title: string; sourceUrl: string };

export default function CoursesPage() {
  const { data, refresh, notify } = useAppState(); const navigate = useNavigate();
  const [selectedId, setSelectedId] = useState(data!.settings.selectedCourseId || data!.courses[0]?.id || ''); const [query, setQuery] = useState('');
  const [newCourse, setNewCourse] = useState(''); const [creatingCourse, setCreatingCourse] = useState(false); const [renaming, setRenaming] = useState(false); const [nameDraft, setNameDraft] = useState('');
  const [contentDraft, setContentDraft] = useState<ContentDraft | null>(null); const [saving, setSaving] = useState(false);
  const importFileRef = useRef<HTMLInputElement>(null);
  const selected = data!.courses.find((course) => course.id === selectedId) || data!.courses[0];
  const filteredCourses = useMemo(() => { const term = query.toLowerCase().trim(); return !term ? data!.courses : data!.courses.filter((course) => course.name.toLowerCase().includes(term) || course.lessons.some((lesson) => `${lesson.title} ${lesson.sourceUrl}`.toLowerCase().includes(term))); }, [data, query]);
  const lessons = useMemo(() => { const term = query.toLowerCase().trim(); if (!selected || !term || selected.name.toLowerCase().includes(term)) return selected?.lessons || []; return selected.lessons.filter((lesson) => `${lesson.title} ${lesson.sourceUrl}`.toLowerCase().includes(term)); }, [selected, query]);

  const createCourse = async () => { if (!newCourse.trim()) return; const course = await api<Course>('/api/courses', { method: 'POST', ...jsonBody({ name: newCourse.trim() }) }); await refresh(); setSelectedId(course.id); setNewCourse(''); setCreatingCourse(false); notify('课程已创建'); };
  const renameCourse = async () => { if (!selected || !nameDraft.trim()) return; await api(`/api/courses/${selected.id}`, { method: 'PATCH', ...jsonBody({ name: nameDraft.trim() }) }); await refresh(); setRenaming(false); notify('课程名称已更新'); };
  const deleteCourse = async () => { if (!selected || !window.confirm(`删除课程“${selected.name}”？课时学习数据和字幕缓存不会被删除。`)) return; await api(`/api/courses/${selected.id}`, { method: 'DELETE' }); await refresh(); setSelectedId(''); notify('课程已删除，共享课时数据已保留'); };
  const saveContent = async () => {
    if (!selected || !contentDraft?.sourceUrl.trim()) return; setSaving(true);
    try {
      if (contentDraft.mode === 'create') await api(`/api/courses/${selected.id}/lessons`, { method: 'POST', ...jsonBody({ sourceUrl: contentDraft.sourceUrl.trim(), title: contentDraft.title.trim() || undefined }) });
      else await api(`/api/lessons/${contentDraft.lessonId}`, { method: 'PATCH', ...jsonBody({ sourceUrl: contentDraft.sourceUrl.trim(), title: contentDraft.title.trim() || undefined }) });
      await refresh(); setContentDraft(null); notify(contentDraft.mode === 'create' ? '学习内容、媒体和字幕已添加' : '学习内容已重新解析');
    } catch (reason) { notify((reason as Error).message); } finally { setSaving(false); }
  };
  const removeLesson = async (lesson: Lesson) => { if (!selected || !window.confirm(`从“${selected.name}”移除“${lesson.title}”？学习记录仍会保留。`)) return; await api(`/api/courses/${selected.id}/lessons/${lesson.id}`, { method: 'DELETE' }); await refresh(); notify('已从课程移除'); };
  const moveLesson = async (lessonId: string, offset: number) => { if (!selected) return; const ids = selected.lessons.map((lesson) => lesson.id); const index = ids.indexOf(lessonId); const target = index + offset; if (target < 0 || target >= ids.length) return; [ids[index], ids[target]] = [ids[target], ids[index]]; await api(`/api/courses/${selected.id}/order`, { method: 'PUT', ...jsonBody({ lessonIds: ids }) }); await refresh(); };
  const retry = async (lesson: Lesson) => { try { await api(`/api/lessons/${lesson.id}/refresh`, { method: 'POST' }); await refresh(); notify('课时已重新解析'); } catch (reason) { notify((reason as Error).message); } };

  const allLessons = data!.courses.reduce((sum, course) => sum + course.lessons.length, 0);
  const importBackup = async (file?: File) => { if (!file) return; try { const payload = JSON.parse(await file.text()); await api('/api/import', { method: 'POST', ...jsonBody(payload) }); await refresh(); notify('备份已导入；课时会在打开时重新解析临时媒体地址'); } catch (reason) { notify(`导入失败：${(reason as Error).message}`); } finally { if (importFileRef.current) importFileRef.current.value = ''; } };
  return <main className="course-manager-page">
    <section className="manager-heading"><div><span className="eyebrow">Course Library</span><h1>课程管理</h1><p>课程和学习内容支持完整增删查改、排序、重新解析和自动去重。</p></div><div className="manager-heading-actions"><input ref={importFileRef} hidden type="file" accept="application/json,.json" onChange={(event) => void importBackup(event.target.files?.[0])} /><button className="detail-command" onClick={() => importFileRef.current?.click()}><Import size={15} />导入备份</button><a className="detail-command" href="/learn/api/export" download><Download size={15} />导出数据</a><button className="manager-create-button" onClick={() => setCreatingCourse(true)}><FolderPlus size={16} />新建课程</button></div></section>
    {creatingCourse && <div className="manager-create-row"><FolderPlus size={17} /><input autoFocus value={newCourse} onChange={(event) => setNewCourse(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void createCourse()} placeholder="输入新课程名称" /><button className="next-button" onClick={() => void createCourse()}><Check size={15} />创建</button><button className="icon-button" onClick={() => setCreatingCourse(false)}><X /></button></div>}
    <section className="manager-summary"><div><Library /><span><strong>{data!.courses.length}</strong><small>课程集</small></span></div><div><Play /><span><strong>{allLessons}</strong><small>课时关系</small></span></div><div><Check /><span><strong>{data!.courses.flatMap((course) => course.lessons).filter((lesson) => lesson.captionStatus === 'ready').length}</strong><small>字幕就绪</small></span></div><div><AlertCircle /><span><strong>{data!.courses.flatMap((course) => course.lessons).filter((lesson) => lesson.importStatus === 'failed').length}</strong><small>需要处理</small></span></div></section>
    <div className="manager-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索课程名称、内容标题或网址" />{query && <button className="icon-button" onClick={() => setQuery('')}><X /></button>}</div>
    <div className="course-library-layout">
      <nav className="course-navigation" aria-label="课程列表"><div className="course-navigation-head"><strong>全部课程</strong><span>{filteredCourses.length}</span></div>{filteredCourses.map((course) => <button className={course.id === selected?.id ? 'active' : ''} key={course.id} onClick={() => setSelectedId(course.id)}><span className="course-nav-icon"><Library size={16} /></span><span><strong>{course.name}</strong><small>{course.lessons.length} 集</small></span></button>)}</nav>
      <section className="course-detail">{selected ? <>
        <div className="course-detail-head">{renaming ? <div className="course-rename"><span>编辑课程名称</span><div><input autoFocus value={nameDraft} onChange={(event) => setNameDraft(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void renameCourse()} /><button className="icon-button" onClick={() => void renameCourse()}><Save /></button><button className="icon-button" onClick={() => setRenaming(false)}><X /></button></div></div> : <div><span>当前课程</span><h2>{selected.name}</h2><p>创建于 {new Date(selected.createdAt).toLocaleDateString('zh-CN')}</p></div>}<div className="course-detail-actions"><button className="detail-command" onClick={() => setContentDraft({ mode: 'create', title: '', sourceUrl: '' })}><Plus size={15} />添加内容</button><button className="icon-button" onClick={() => { setNameDraft(selected.name); setRenaming(true); }}><Pencil /></button><button className="icon-button danger" onClick={() => void deleteCourse()}><Trash2 /></button></div></div>
        {contentDraft && <div className="content-form"><div className="content-form-heading"><span>{contentDraft.mode === 'create' ? '新增学习内容' : '编辑并重新解析'}</span><button className="icon-button" onClick={() => setContentDraft(null)}><X /></button></div><label><span>标题（可选）</span><input value={contentDraft.title} onChange={(event) => setContentDraft((current) => current && ({ ...current, title: event.target.value }))} placeholder="留空则从页面读取" /></label><label className="wide-field"><span>公开课程网页地址</span><input value={contentDraft.sourceUrl} onChange={(event) => setContentDraft((current) => current && ({ ...current, sourceUrl: event.target.value }))} onKeyDown={(event) => event.key === 'Enter' && void saveContent()} placeholder="https://learn.deeplearning.ai/..." /></label><button className="next-button" disabled={saving} onClick={() => void saveContent()}>{saving ? <LoaderCircle className="spin" /> : <Save size={15} />}{saving ? '解析中' : '保存'}</button></div>}
        <div className="course-item-head"><span>学习内容</span><span>字幕与翻译</span><span>操作</span></div><div className="course-item-list">{lessons.map((lesson, index) => <article className="course-item" key={lesson.id}><span className="course-item-index">{String(index + 1).padStart(2, '0')}</span><div className="course-item-title"><strong>{lesson.title}</strong><small>{new URL(lesson.sourceUrl).hostname} · {lesson.sourceVideoId || '等待解析'}</small></div><div className="course-item-progress"><span className={lesson.captionStatus === 'ready' ? 'learned' : ''}>{lesson.captionStatus === 'ready' ? `${lesson.cueCount} 句字幕` : lesson.importStatus === 'failed' ? '解析失败' : '等待解析'}</span><small>{lesson.translationStatus === 'ready' ? '中文已缓存' : lesson.translationProgress > 0 ? `${Math.round(lesson.translationProgress * 100)}% 已免费缓存` : '免费按需翻译'}</small></div><div className="course-item-actions"><button className="open-course-item" onClick={() => navigate(`/learn/${lesson.id}`)}><Play size={14} />进入学习</button><button className="icon-button" disabled={index === 0} onClick={() => void moveLesson(lesson.id, -1)} title="上移"><ArrowUp /></button><button className="icon-button" disabled={index === lessons.length - 1} onClick={() => void moveLesson(lesson.id, 1)} title="下移"><ArrowDown /></button><button className="icon-button" onClick={() => setContentDraft({ mode: 'edit', lessonId: lesson.id, title: lesson.title, sourceUrl: lesson.sourceUrl })} title="编辑"><Pencil /></button><button className="icon-button" onClick={() => void retry(lesson)} title="重新解析"><RefreshCw /></button><button className="icon-button danger" onClick={() => void removeLesson(lesson)} title="移除"><Trash2 /></button></div></article>)}{!selected.lessons.length && <div className="empty-course"><Library /><strong>这个课程还没有学习内容</strong><span>添加公开课时网址后会自动解析视频和独立字幕。</span><button className="next-button" onClick={() => setContentDraft({ mode: 'create', title: '', sourceUrl: '' })}><Plus size={15} />添加内容</button></div>}</div>
      </> : <div className="empty-course"><Library /><strong>还没有课程</strong></div>}</section>
    </div>
  </main>;
}
